[package]
name = "imfconv"
version = "3.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.8"
image = "0.24.5"
rand = "0.8.5"
walkdir = "2.3.2"
